name: Run the tests

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            label: linux-64
            prefix: /usr/share/miniconda3/envs/spartacus
    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: 24.11.3-2
          use-mamba: true
          activate-environment: spartacus
          environment-file: environment.yml
        
      - name: Print conda info
        run: | 
          conda info
          conda list

      - name: Install extra dependencies
        run: conda install pytest-cov black pytest pytest-cov codecov -cconda-forge

      - name: Run the actual tests
        run: pytest -v --color=yes --cov-report term-missing --cov=spartacus tests
        
      - name: Upload coverage to Codecov
        run: codecov
        if: matrix.label == 'linux-64'

      - name: Test installed version of spartacus
        run: |
          pip install -e . --no-deps
          conda list